### ISSUE TITLE
copy / paste in box issue

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#20]
copy / paste a text in any boxes is disabled.

MacOS 14.0

**Comment by pd-l2ork** [comment]
Which box? Generic PD object box? And where are you copying text from?

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by 60-hz** [comment]
Copy/paste are disabled on any box field (object, message...)

**Comment by pd-l2ork** [comment]
Thanks for the report, this was also just fixed and will be in the next release.
