### ISSUE TITLE
search box shows old references

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#21]
The suggestions in the object search box are old typed objects references, many are wrong/outdated objects.
It even shows references from my other pd distributions.

Is there a way to clear them?

Removing "Pd-L2Ork" folder in Application support and "org.puredata.pd-l2ork.plist" in preferences didn't help.

MacOS 14.0

**Comment by pd-l2ork** [comment]
Are you talking about auto complete inside generic PD object or the search
box inside browser?

If generic PD object, you can manually erase appropriate file in your
~/.pd-l2ork folder (on OSX/Linux systems) or %APPDATA%/Pd-L2Ork on Windows.
This one stores any typed object that was successfully created before. That
way you can easily recreate it again.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by 60-hz** [comment]
Ok thanks, ~/.pd-l2ork folder was what I was searching for!

**Comment by pd-l2ork** [comment]
Sure. Perhaps I should keep custom autocompletions only until you close Pd-L2Ork?

**Comment by 60-hz** [comment]
I was just confused because some object like [anysoundfiler] and [readanysf~] could not build despite been in the list of suggestions. 
I think right now the behavior is too add custom autocompletion only if the object could be built, which seems ok.

**Comment by pd-l2ork** [comment]
I see. Lemme investigate this further.

On a related note, if you have an entry that you don't need anymore, select it in the autocomplete popup and pres CTRL+Y twice (2nd is to confirm).

**Comment by pd-l2ork** [comment]
OK, so I just made a commit that fills autocomplete options in a way that includes prefixes. This, however, will work only for objects inside the extra folder. Others will have to be added manually. All this still does not solve issues like when you use the [declare] object to expose pd-l2ork to a particular folder, which then enables you to create those objects without prefix. Neither does this prevent you from creating a confusion in case you use same object names as another library. So, there will be always room for user misconfiguration. That said, this should hopefully work a bit better.
