### ISSUE TITLE
[arduino_analog_out] issue

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#22]
pwm / servo don't work properly because pwm need to be a float between 0 and 1 and [split] object doesn't allow float, only int.

replacing [split 0 1] with object [moses 1] fixed the problem.

**Comment by pd-l2ork** [comment]
Why not simply take the value (which I think it is 10-bit) and divide it by 1024? Also, what abstraction are you referring to?

**Comment by 60-hz** [comment]
Sorry, the abstraction name was in the title: arduino_analog_out.pd

I seems there is a mistake here in pd-l2ork

**Comment by pd-l2ork** [comment]
Thanks. This has been fixed.
