### ISSUE TITLE
Ui is laggy under MacOs

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#23]
The UI has some lag issues under MacOS.

https://github.com/pd-l2ork/pd-l2ork/assets/5449719/61d80119-b88e-41a8-a759-b67ba95466e9

**Comment by pd-l2ork** [comment]
Looks like stuff within the window is fine, but resizing of the window is slow? If this is what you mean, try doing the same with Chrome or Chromium browsers. If their windows also resize slowly, then this is a limitation of Chromium, as that is what pd-l2ork GUI uses, and it is unlikely we will be able to make the window resizing any faster.

I will leave this issue open until you've had a chance to respond.

**Comment by 60-hz** [comment]
All the gui have little slowdown every 2seconds, object moving, resizing,
click for r even gem get the same slowdown. I checked my host file under
macos but it looks ok (because I guess the core and GUI still communicate
using network).

**Comment by pd-l2ork** [comment]
I see. Can you check if your DSP is on and if it is, can you try the same with the DSP off?

**Comment by 60-hz** [comment]
I cleared all preferences and rebooted, it looks to be much better now.
So I guess it was my system fault... sorry for the noise ;)

I am closing this.
