### ISSUE TITLE
listbox is missing

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#24]
The listbox is part of basic ui of puredata and pd-l2ork is missing it.

I guess this is because pd-l2ork is based on a old version of pd...

**Comment by pd-l2ork** [comment]
Yes, this is already on a TODO list. I am working as fast as I can addressing the remaining issues existing issues and will address catching up with latest pd shortly thereafter. Please note this is also a duplicate of #8 , so I will close this one.
