### ISSUE TITLE
Pd-l2ork Flatpak Can't Launch because of Read-only Filesystem

### ISSUE THREAD

**Issue by brandflake11** [pd-l2ork/pd-l2ork#27]
Hello (probably Ico),
I am on Fedora Universal Blue with the Silverblue-main image (it is an immutable Linux distro) and I cannot get pd-l2ork from flathub, version 20231129, to launch. 

When trying to run the flatpak, I get this error message:
`$ flatpak run io.github.pd_l2ork.Pd_L2Ork
bwrap: Can't mkdir parents for /app/extensions/Plugins: Read-only file system
error: ldconfig failed, exit status 256
`

I'm not quite sure what the problem is, but the flatpak was working before. Maybe this has to do with some kind of flatpak permissions or because of the distro being immutable. 

Let me know what I can do to help out with this.

**Comment by pd-l2ork** [comment]
Thanks for the feedback, Brandon. Did it work before on this specific (immutable type of) distro?

**Comment by brandflake11** [comment]
Yes, it was working before. I'll also try it on another universal blue computer I have that has a different image on it.

**Comment by pd-l2ork** [comment]
Thanks for the update. I wonder if there is something unique with Fedora immutable install since pd-l2ork runs just fine on Stream Deck that is also immutable. IIRC /apps folder is reserved for flatpak installs system-wide. Will need to check/confirm.

**Comment by brandflake11** [comment]
I do know fedora uses SElinux, so I dont know if that has anything to do with it. I'm just speculating, it might be something else entirely.

**Comment by pd-l2ork** [comment]
Following up on this, have you tried installing with sudo privileges if you are installing flatpak system-wide?

**Comment by brandflake11** [comment]
Installing the flatpak with sudo didn't seem to change anything unfortunately. I also have tried installing only for the user and I get the same error.

**Comment by brandflake11** [comment]
After our discussion in person of trying to remove the LADSPA env from the flatpak .yml build file, I followed the flatpak readme to build pd-l2ork on my system, and got this error on the last line:
```

$ flatpak run org.flatpak.Builder --verbose --install ./build io.github.pd_l2ork.Pd_L2Ork.yml --force-clean --user

flatpak run org.flatpak.Builder --verbose --install ./build io.github.pd_l2ork.Pd_L2Ork.yml --force-clean --user
FB: Running: git config --get user.email
FB: Running: git config --get user.name

(flatpak-builder:2): flatpak-builder-ERROR **: 12:51:56.564: Failed to load included manifest (/var/home/brandon/Sourceforge/io.github.pd_l2ork.Pd_L2Ork/shared-modules/glu/glu-9.json): Failed to open file “/var/home/brandon/Sourceforge/io.github.pd_l2ork.Pd_L2Ork/shared-modules/glu/glu-9.json”: No such file or directory
```

**Comment by pd-l2ork** [comment]
Looks like it is not pulling the supporting build libraries. Not sure why. Maybe commenting out that line somehow broke something in the yml file? BTW you need to be on the Internet for the build to be successful.

**Comment by brandflake11** [comment]
Is there a submodule that I need to pull? It looks like the ./shared-modules folder is empty.

**Comment by pd-l2ork** [comment]
My apologies. You should clone the pd-l2ork project git and then go to the packages/linux_flatpak folder, edit the yml file in there (just like we did), and then run:

`git submodule update shared-modules/`

If that does not work, try:

`git submodule init shared-modules/
git submodule update shared-modules/
`

Then run the commands in the README.md

Hope this helps.

**Comment by brandflake11** [comment]
I compiled and installed the flatpak myself without the ladspa plugin env line, but it still has the same issue.

**Comment by brandflake11** [comment]
This fixed it for me, thanks!
