### ISSUE TITLE
Add AUR package description

### ISSUE THREAD

**Issue by OctopusET** [pd-l2ork/pd-l2ork#43]
https://aur.archlinux.org/packages/pd-l2ork-bin
I just made an AUR package for ArchLinux.

I'm planning to make `pd-l2ork` and `pd-l2ork-git` too.

**Comment by pd-l2ork** [comment]
This is fantastic. Will you be actively keeping this up-to-date with the latest releases (we just had a major release 2 days ago)? If so, would it be ok if I add this to the download links? Thanks.

**Comment by OctopusET** [comment]
Yeah sure, it would be great if you add this to the download links.
I will try to make it up-to-date.

**Comment by OctopusET** [comment]
It would be great if there's a list of versions

**Comment by pd-l2ork** [comment]
Great! Thank you. BTW keep an eye on tags. That is when I make major releases. Latest was a couple days ago on Sept. 30th, 2024 (tag 20240930). Another one is coming up on Monday Oct. 14th, 2024.  Look for a 20241014 tag once added to the git commit. Hope this helps.

**Comment by OctopusET** [comment]
How about using `Release` feature in github? It would be easier to manage for you too. Like you can just link the package link instead of actually uploading on website.

**Comment by pd-l2ork** [comment]
Thank you for a suggestion. The problem is that there appears to be a limit to how large releases can be and given Pd-L2Ork is not small by any stretch of imagination github may not be able to host releases. Will investigate further...

In the meantime, I just released 20241111 version which is also tagged accordingly.

**Comment by OctopusET** [comment]
I updated the package, AFAIK github allows uploads up to 2GB

**Comment by pd-l2ork** [comment]
Thank you. Is that 2GB in total, or per release?

**Comment by OctopusET** [comment]
Each files
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

**Comment by OctopusET** [comment]
@pd-l2ork Did you remove previous releases?

**Comment by pd-l2ork** [comment]
Yes. It was a premature release (we had the runner originally configured to auto build). Thank you for maintaining and updating the AUR package.
