### ISSUE TITLE
Issues on Ubuntu 24.04

### ISSUE THREAD

**Issue by znmeb** [pd-l2ork/pd-l2ork#46]
I'm trying to build and install on Ubuntu 24.04 LTS. So far I've run into two issues:

1. Build: the build process requires `fakeroot`, which isn't in the listed build dependencies.
2. Once built, there are some missing dependencies:

```
$ sudo apt-get install -f ./Pd-L2Ork-full-20240327-rev.dcafbeb22-x86_64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pd-l2ork' instead of './Pd-L2Ork-full-20240327-rev.dcafbeb22-x86_64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pd-l2ork : Depends: python2 but it is not installable
            Depends: libgconf-2-4 but it is not installable
            Recommends: pulseaudio-utils but it is not going to be installed
            Recommends: ladspa-foo-plugins but it is not installable
            Recommends: slv2-jack but it is not installable
            Recommends: ubuntustudio-audio-plugins but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by pd-l2ork** [comment]
Hi, and thanks for the bug report. This is probably because of the change in package names between Ubuntu 22.04 and 24.04. Until this is fixed (which should be in the next couple of days), please try the one available on our website which has these manually amended.

**Comment by znmeb** [comment]
Thanks!! I didn't see the link on the website. If there's a package I don't need to compile it!

**Comment by pd-l2ork** [comment]
My bad. I just realized we only have 20.04 and 22.04 builds (and have updated the README.md accordingly). This may take a bit longer to do as I still don't have access to a 24.04 machine. In the meantime, have you considered using Flatpak instead? It should work just as well.

**Comment by znmeb** [comment]
Yes, I have the Flatpak and am using it on Fedora 40 Silverblue. I'm looking for a build to run in a "Noble Numbat" container, and there are some issues with running Flatpaks in containers with my container hosting setup. 

I'm on the "dev" mailing list - I can test the build from source in 24.04 on either WSL or in a container if there's someone who knows the source layout.

**Comment by pd-l2ork** [comment]
Thanks for the info. I think once we transition to 24.04 we will be able to look into this. Until then, can you run a 22.04 container?

As for 4 variants, well, that is both the strength and weakness of open source. Pd-L2Ork is built on Pd-Extended, which until recently has been abandoned. Purr-Data is an off-shoot of Pd-L2Ork 1.x, whereas Pd-L2Ork 2.x builds upon Purr Data. Pd is the original project from which all the other forked. In the coming weeks, we will be merging updates in Pd, so at that point Pd-L2Ork should hopefully be an all-in-one solution. Hope this helps.

**Comment by znmeb** [comment]
Thanks! I have pretty much decided I only need Pd-L2Ork, although for the moment I'm installing all the Pure Data packages in the Ubuntu 24.04 repositories in the container.

**Comment by pd-l2ork** [comment]
So the new builds are now hosted on github. There you will find the latest Ubuntu LTS, as well as the flatpak. Hope this helps.
