### ISSUE TITLE
remove mentionings to "purr data"

### ISSUE THREAD

**Issue by porres** [pd-l2ork/pd-l2ork#5]
I got this error referring to pd-l2ork as "purr data", maybe you wanna change that

<img width="537" alt="Screen Shot 2021-11-29 at 18 37 07" src="https://user-images.githubusercontent.com/5360142/143946976-1526fbd8-8de5-4be1-8e08-f12f5d715f24.png">

**Comment by pd-l2ork** [comment]
I just committed a patch that fixes this. thanks for the report.

**Comment by porres** [comment]
i also thought about other mentionings => https://github.com/pd-l2ork/pd-l2ork/search?p=3&q=purr

**Comment by pd-l2ork** [comment]
The remaining changes have now been committed. Closing this issue.
