### ISSUE TITLE
OSX (macOS actually) download not working on arm mac

### ISSUE THREAD

**Issue by porres** [pd-l2ork/pd-l2ork#55]
I mean the download from https://l2ork.music.vt.edu/main/make-your-own-l2ork/software/ 

tested with M3 macbook air, Sonoma.

**Comment by pd-l2ork** [comment]
Thanks for the report. I found the problem and fixed it. Looks like the issue affected all Macs, regardless the OS due to changes in the way code signing works. Tested the latest OSX release (Pd-L2Ork-full-20240930-rev.6461c294-x86_64.dmg) on both Intel and ARM Macs.

**Comment by porres** [comment]
> Tested the latest OSX release

Hi, nitpicking here, there's no 'OSX' anymore, it's "macOS" since 2016, so it was then 'macOS 10' instead 'OSX' for the last versions, and since Big Sur it moved on to '11', and so on... we're now at "macOS 15" Sequoia.

Anyway, I suggest you change the link name to just 'macOS' and drop the old 'OSX' nomenclature.
