### ISSUE TITLE
lading externals, binaries supported?

### ISSUE THREAD

**Issue by porres** [pd-l2ork/pd-l2ork#61]
Hi, I'm having trouble testing some objects of my library (ELSE), like the ones that operate with multichannel connections support, which I would like to test now that Pd-L2ork supports it.

But I was just unable to load the binaries and I don't know why. What are the supported format? I couldn't load .d_fat binaries, for instance.

Pd now has new file formats by the way, see Table 4.1 in https://msp.ucsd.edu/Pd_documentation/resources/chapter4.htm#s4.1.2.1

**Comment by pd-l2ork** [comment]
Pd-L2Ork does not guarantee binary compatibility because our data structures increasingly diverge from vanilla's. Recompiling them for pd-l2ork will likely fix your problem. Hope this helps.

**Comment by porres** [comment]
> Recompiling them for pd-l2ork will likely fix your problem. Hope this helps.

hmm, where can we learn how to do that?

**Comment by pd-l2ork** [comment]
Building should be near identical. For instance, the cyclone library is similar in its source structure. In fact, I could take the source and build it for vanilla as long as I have the right paths to include files. See the externals subfolder. If you have a specific external's source, send it to me and I can look into it once I am done with the upcoming L2Ork International Ensemble performance.

**Comment by porres** [comment]
> If you have a specific external's source, send it to me and I can look into it once I am done with the upcoming L2Ork International Ensemble performance.

Well, it's my ELSE library, see https://github.com/porres/pd-else

It's quite huge and I wanted to test objects with multichannel support (I got about 90 of them).

It'd be great to have ELSE working in Pd-L2ork by the way, Albert worked on being able to include it in Purr Data a while ago, see https://github.com/agraef/purr-data/releases/tag/2.19.2%2BELSE

If you get Pd-L2ork fully up to date in Vanila, then I think all objects without tcl/tk code should work.

Ideally and eventually I/we could port the tcl/tk code and hopefully include this library over here, but you have many other priorities, like getting up to date to Pd and update the externals.
