### ISSUE TITLE
Snap to Grid in Patch Editor

### ISSUE THREAD

**Issue by DWW256** [pd-l2ork/pd-l2ork#7]
In Purr-Data, elements automatically snapped to the editing grid.  I found this function supremely useful for organizing patches.  It appears, for some reason, that this feature has not made it into Pd-L2Ork.  Could you consider re-adding it?  Or at least adding a toggle in the "Edit" menu or something?  Thanks.

**Comment by pd-l2ork** [comment]
Hi, thanks for your comment. I will look into it to see if it can be easily merged. I seem to recall there were some weird limitations that I wanted to address before merging it. Hope this helps.

**Comment by pd-l2ork** [comment]
Forgot to update there that this has been now available since this summer. See the preferences for options.
