### ISSUE TITLE
pd version update

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#8]
Thanks for the great work.
I see that pd-l2ork use pd-0.48 and I was wondering if there is any plan to update it to the last version in order to benefit from all the new features ( list atom, [file] object, inlet~ message fowarding etc...) and fixes.

**Comment by pd-l2ork** [comment]
Thank you for your kind words. There is definitely plan to do this. I am still cleaning up the transition from 1.x to 2.x and as soon as this is done, I will focus my energy on catching up with features added to vanilla since. What would be super helpful is if you could list items you have noticed missing, as that will make porting thins a lot easier. Thanks.

**Comment by 60-hz** [comment]
I think the best for an up to date list of new features is to take a look at the release note:
http://msp.ucsd.edu/Pd_documentation/x5.htm#s1

From a GUI rewrite perspective, here is the one I see:

- New "list" box, like number and symbol but allows lists in addition to single atoms. You can scroll up and down on any of the numbers in a list as if it were a number box. All boxes (number, symbol, list) can now set different sizes and you can also double-click on them to activate a "real" editor you can copy/paste from/to.
- New method for garrays to set colors, line width, visibility, display style and disable mouse editing
- Some improvements to label handling in IEMguis (more info [here](https://github.com/pure-data/pure-data/issues/1638))
- Improved window positioning. (-> Every "new" windows are a bit shifted so they do not  appear perfectly superimposed).
- Pd's GUI checks that Pd actually exits when asked to and if not, kills it to prevent rogue invisible pd instances from collecting behind the scenes.

**Comment by pd-l2ork** [comment]
Thanks for the info. I will look into these. However, please note that
pd-l2ork already has the following (please see below):

On Sat, Oct 15, 2022 at 4:18 PM Raphael Isdant ***@***.***>
wrote:

> I think the best for an up to date list of new features is to take a look
> at the release note:
> http://msp.ucsd.edu/Pd_documentation/x5.htm#s1
>
> From a GUI rewrite perspective, here is the one I see:
>
>    - New "list" box, like number and symbol but allows lists in addition
>    to single atoms. You can scroll up and down on any of the numbers in a list
>    as if it were a number box. All boxes (number, symbol, list) can now set
>    different sizes and you can also double-click on them to activate a "real"
>    editor you can copy/paste from/to.
>
> pd-l2ork has a dropdown object for this. All gatoms are resizable
(width-wise). You can also cut and paste into symbol gatom, as well as
append (shift+click).

>
>    - New method for garrays to set colors, line width, visibility,
>    display style and disable mouse editing
>
> pd-l2ork has had array color setting options for several years now.
Disabling editing is the only option that does not exist (but does exist
for other iemgui and gatom objects).

>
>    - Some improvements to label handling in IEMguis (more info here
>    <https://github.com/pure-data/pure-data/issues/1638>)
>
> iemgui numbox2 in pd-l2ork already automatically adjusts the number font
inside it and allows resizing using a drag-able corner (this is true of
most GUI objects in pd-l2ork, including GOP and labels).

>
>    - Improved window positioning. (-> Every "new" windows are a bit
>    shifted so they do not appear perfectly superimposed).
>
> I am not sure if this is an issue with pd-l2ork. Will check.

>
>    - Pd's GUI checks that Pd actually exits when asked to and if not,
>    kills it to prevent rogue invisible pd instances from collecting behind the
>    scenes.
>
> Not sure if this is also an issue for pd-l2ork, since we use nw.js
(chromium) and SVG shapes to draw patches, but will investigate.

**Comment by 60-hz** [comment]
Thanks, for listing some of the cool features of the pd-l2ork GUI. (I see that menu dropdown have not the same exact purpose than the new "listbox" atom, which is a core function and appear iun many helpfiles now).
Moreover, a pd update would offer all the new objects listed in the release note and the fixes since the vanilla pd UI has barely changed from version to version.

**Comment by pd-l2ork** [comment]
We are now on 0.54 minus the list box which should be added in the coming weeks. I will therefore close this issue. Please feel free to reopen if you encounter any other issues.
